### ISSUE TITLE
Trailer Request Lizard Class C 450/455/460 Low Loader

### ISSUE THREAD

**Issue by Reapz2022** [ddewar/FS22_UniversalAutoloadModhubAddon#26] opened 2022-08-17 23:26 UTC
Hey there , Such a great job on the mod's few question/ 1 Request if possible 
If you could maybe add support for Lizard Class C 450/455/460 Low Loader Link as followed.
https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=246502&title=fs2022

Also is there any way to make the pallets for furniture stack 2 high ?

**Comment by ddewar** [comment] 2022-08-18 00:55
I will be sure to put this in the next release. I will keep you updated here when I get it in. 

Base game furniture pallet? Which trailer are you trying to load them on to? I can take a look at what's happening, but they're probably just too tall. The pallet itself is configured to stack, so I don't think that is the problem. Let me know and I can always send you a configuration better tuned for the trailer you're trying to use.

**Comment by Reapz2022** [comment] 2022-08-18 13:18
Yea the basegame pallets , It was the 20Ft Gooseneck Trailers Pack From 82Studio's , 
 https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=247589&title=fs2022
 
 It work great the way it , no need to send anything , sure you are busy , But thank you for the great mod ,

**Comment by M0lyk** [comment] 2022-08-19 12:42
Hi, can you please add this trailer ?

https://www.farming-simulator.com/mod.php?mod_id=237992&title=fs2022

**Comment by ddewar** [comment] 2022-08-19 13:40
> Hi, can you please add this trailer ?
> 
> https://www.farming-simulator.com/mod.php?mod_id=237992&title=fs2022

Hey @M0lyk, I'll see what I can do. Would you mind opening a separate issue so I can track the# requests separately? Thanks!

**Comment by ddewar** [comment] 2022-08-19 14:05
@Reapz2022 is your 20ft gooseneck trailer pack not loading 2 like this?

![image](https://user-images.githubusercontent.com/15822357/185636311-09982847-4472-42af-8bf0-f698cb460b64.png)

Or did you want 3 high?

**Comment by Reapz2022** [comment] 2022-08-21 22:01
Not not 3 high , Just too high and might dont load like that 

![image](https://user-images.githubusercontent.com/111468729/185812591-c1c961fb-ec1d-4bba-8ffe-7d49282cfa02.png)

And the only mod i got installed is that truck / The 20FT trailer / And Your AutoLoad

**Comment by Reapz2022** [comment] 2022-08-21 22:04
![image](https://user-images.githubusercontent.com/111468729/185812754-e4a75a62-5f3d-4629-8a93-ba91355e1cdc.png)
This was tryin to load them outside the truck and it just remove the straps and says loading area is full

**Comment by Reapz2022** [comment] 2022-08-21 22:52
Here a little video might explain it better 
5Min Video , In this video i only use the mods that are needed , 
https://www.youtube.com/watch?v=helFaGljMaE&ab_channel=SuijiiN

**Comment by ddewar** [comment] 2022-08-25 14:49
Still working on this not sure what's going on yet. Been talking with Loki about it.

**Comment by Reapz2022** [comment] 2022-08-26 02:01
Ok perfect

**Comment by ddewar** [comment] 2022-08-27 15:43
So, I finally got to the Class C part of this, I think that mod is already supported? I think the name of the zip file is actually 'FS22_36ftLowLoader' Please let me know if I am looking at the wrong mod?

Still working on stacking issue.

**Comment by ddewar** [comment] 2022-08-27 18:42
Okay, so I have been trying to wrap my head around this for a while, I finally figured it out. 

In my test environment, one of the mods I added changed the weight of furniture pallets. As a result of this, UAL was allowing my pallets to stack higher. The issue is each pallet is 1.1 tons. UAL is set to make sure it does not over stack heavy pallets on light trailers. So not sure there is anything I can do on this one. Hopefully in a future version of UAL we can use different loading algorithms to avoid this kind of limitation.

Hopefully this explanation helps. Let me know if there's anything else I can do.

**Comment by Reapz2022** [comment] 2022-08-27 23:03
So for the Class C yes it is working i should of tested it myslef I am sorry ,  tho there is on problem with it if you use the Bumper pull or Gooseneck configuration it try and put the pallets on a Neck part of the trailer that is no longer there , Cause of the change of the configuration , But if you use it as default configuration the deck is there so it work perfect , As for the 20FT Gooseneck i installed the liftable pallet mod and everthing working as it should now thanks.

Here little 1min video showing the ClassC trailer ,
https://www.youtube.com/watch?v=AEJ0H8QKg3o&ab_channel=SuijiiN

Again sorry for asking i should of tested it befor askin about it.

**Comment by ddewar** [comment] 2022-08-28 00:31
Not a problem at all! The name of the mod is different from the zip name, so it kinda gets lost in the shuffle. I clearly didn't even remember either, because I tried to configure it again and confused myself. 😂

I'll take a look at the bumper pull and gooseneck. Loki made some changes around configurations. It might be from that. I'll try to find a solution soon.

**Comment by ddewar** [comment] 2022-08-28 16:20
Thanks for pointing this out. I just never configured the other versions when we added multiple loading zones. Should be fixed in the next release.

**Closed** 2022-08-28 16:19 UTC
Labels: bug, enhancement mod support, question
