### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by judg393** [ddewar/FS22_UniversalAutoloadModhubAddon#67] opened 2023-02-02 15:11 UTC
Hi Dan 

I usually use a sym link folder and GitHub desktop app to sync any adjustments to UAL and your add on to my pc so I'm always up to date 

Trying to sync changes made after the 13th December cause my game to crash with lua warnings about a script in UAL add on logs attached. Might not be an issue or an issue that you plan to fix with next release but thought I'd flag it 

@loki79uk same thing seems to happen if I just updateUAL  see log2 notsure i f they are linked

**Comment by judg393** [comment] 2023-02-02 15:15
Logs to follow sorry!

**Comment by judg393** [comment] 2023-02-02 16:19
[log.txt](https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/files/10571011/log.txt)
[log2.txt](https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/files/10571012/log2.txt)

**Comment by loki79uk** [comment] 2023-02-02 18:16
The issue here was caused by a typo in the pull request that I added:
https://github.com/loki79uk/FS22_UniversalAutoload/pull/153

I don't know how configurable your symlink folder system is, but really you should only play using commits that have a version tag, or ideally you could use the URL:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/latest

**Comment by judg393** [comment] 2023-02-03 11:10
Cheers guys I do tend to only update when there is a release but   I thought I was being clever by keeping everything up to date 😂 I believe I'm running latest UAL fine. I'll wait in future for release tags to appear before updating my folder.

**Comment by ddewar** [comment] 2023-03-17 04:59
Is this resolved now? Can I close this?

**Comment by judg393** [comment] 2023-03-24 12:51
Sorry yes it is 😀

**Closed** 2023-03-24 12:52 UTC
